// <auto-generated />
using System;
using Gdekor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gdekor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714212655_SzunetCsoprtIdopont")]
    partial class SzunetCsoprtIdopont
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gdekor.Munka_Ora", b =>
                {
                    b.Property<string>("MOra_ID")
                        .HasColumnType("text");

                    b.Property<string>("Letrehoz")
                        .HasColumnType("text");

                    b.Property<string>("M_Kezdete")
                        .HasColumnType("text");

                    b.Property<string>("M_Nap_ID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("M_Vege")
                        .HasColumnType("text");

                    b.HasKey("MOra_ID");

                    b.HasIndex("MOra_ID");

                    b.HasIndex("M_Nap_ID");

                    b.ToTable("Munkaorak_Tbl");
                });

            modelBuilder.Entity("Gdekor.Munka_Szunet", b =>
                {
                    b.Property<string>("MSzunet_ID")
                        .HasColumnType("text");

                    b.Property<string>("Letrehoz")
                        .HasColumnType("text");

                    b.Property<string>("MSzunet_CsoportID")
                        .HasColumnType("text");

                    b.Property<string>("M_Nap_ID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sz_Kezdete")
                        .HasColumnType("text");

                    b.Property<string>("Sz_Vege")
                        .HasColumnType("text");

                    b.HasKey("MSzunet_ID");

                    b.HasIndex("MSzunet_ID");

                    b.HasIndex("M_Nap_ID");

                    b.ToTable("MunkaSzunetek_Tbl");
                });

            modelBuilder.Entity("Gdekor.Munkanap", b =>
                {
                    b.Property<string>("MNap_ID")
                        .HasColumnType("text");

                    b.Property<string>("M_Datum")
                        .HasColumnType("text");

                    b.Property<string>("Prof_ID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Projekt_ID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MNap_ID");

                    b.HasIndex("Prof_ID");

                    b.HasIndex("Projekt_ID");

                    b.ToTable("Munkanaptok_Tbl");
                });

            modelBuilder.Entity("Gdekor.Projekt", b =>
                {
                    b.Property<string>("Pro_ID")
                        .HasColumnType("text");

                    b.Property<string>("ProValos_Veg")
                        .HasColumnType("text");

                    b.Property<string>("Pro_Allapot")
                        .HasColumnType("text");

                    b.Property<string>("Pro_Bevetel")
                        .HasColumnType("text");

                    b.Property<string>("Pro_KikDolgoznak")
                        .HasColumnType("text");

                    b.Property<string>("Pro_Koltseg")
                        .HasColumnType("text");

                    b.Property<string>("Pro_Leir")
                        .HasColumnType("text");

                    b.Property<string>("Pro_Nev")
                        .HasColumnType("text");

                    b.Property<string>("Pro_Profit")
                        .HasColumnType("text");

                    b.Property<string>("Pro_Terv_Kezdet")
                        .HasColumnType("text");

                    b.Property<string>("Pro_Terv_Veg")
                        .HasColumnType("text");

                    b.Property<string>("Pro_Valos_Kezdet")
                        .HasColumnType("text");

                    b.HasKey("Pro_ID");

                    b.ToTable("Projektek_Tbl");
                });

            modelBuilder.Entity("Gdekor.Resztvevo_Projektben", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("Pro_ID")
                        .HasColumnType("text");

                    b.Property<string>("User_ID")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("Pro_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("ResztvevokProBen_Tbl");
                });

            modelBuilder.Entity("Gdekor.UserProfil", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AnyjaNeve")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nev")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfKepUtovnal")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("SzemelyiSzam")
                        .HasColumnType("text");

                    b.Property<string>("SzulHely")
                        .HasColumnType("text");

                    b.Property<string>("SzulIdo")
                        .HasColumnType("text");

                    b.Property<string>("Tel_Korzet")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Gdekor.Munka_Ora", b =>
                {
                    b.HasOne("Gdekor.Munkanap", null)
                        .WithMany()
                        .HasForeignKey("M_Nap_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gdekor.Munka_Szunet", b =>
                {
                    b.HasOne("Gdekor.Munkanap", null)
                        .WithMany()
                        .HasForeignKey("M_Nap_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gdekor.Munkanap", b =>
                {
                    b.HasOne("Gdekor.UserProfil", null)
                        .WithMany()
                        .HasForeignKey("Prof_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gdekor.Projekt", null)
                        .WithMany()
                        .HasForeignKey("Projekt_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gdekor.Resztvevo_Projektben", b =>
                {
                    b.HasOne("Gdekor.Projekt", null)
                        .WithMany()
                        .HasForeignKey("Pro_ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Gdekor.UserProfil", null)
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Gdekor.UserProfil", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Gdekor.UserProfil", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gdekor.UserProfil", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Gdekor.UserProfil", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
